- name: Install httpd and php for CentOS
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: "httpd- Restarting/Enabling"
  service:
    name: httpd
    state: restarted
    enabled: true

- name: Install Mariadb service to CentOS
  yum:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "CentOS"

- name: "mariadb- Restartning/Enabling"
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: Install Nagios Monitoring tool to CentOS
  yum:
    name:
      - nagios
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

