---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Create a banner motd for remote servers ssh connection
    copy:
      content: "Ansible Manage by daniel\n"
      dest: /etc/motd
- hosts: Debian
  become: true
  roles:
    - Debian

- hosts: CentOS
  become: true
  roles:
    - CentOS
